language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

os:
  - linux

install:
  - pip3 install -r requirements.txt

script:
  - python3 setup.py test

deploy:
  - provider: pypi
    user: statoil-travis
    password:
      secure: ...
    on:
      tags: true
